### PR TITLE
Expire members during data rx, members with status PROC should not login

### PR DESCRIPTION
**Pull request by francoisbessette**
These are changes I did mainly to help ACC Montreal who are importing members from 3 different sections.
The main issue was the plugin expiry processing. That processing was going over the whole user database and was expiring anybody with an expired valid_to date, and changing their role. The new role would often be set incorrectly, because the plugin was following the config of whatever context it happened to be running. For instance, if the plugin was configured to import members from Montreal, and the expiry phase found a Outaouais user to be expired, it would change its role to old_member_mtl or similar name (not sure I have the right name).

The solution is to remove the expiry sequence, and expire members when we receive the data from 2mev. This is possible because recently (fall 2023?) 2mev started sending notifications when a member 'expires'.  In other words, now that 2mev tells us when a member expires, we no longer need the plugin to have a safeguard function scanning the whole database of users and watching for expired members.  

It also makes the processing much faster because the plugin only processes a few entries, and does not need to scan the whole database of users each times it runs.  

**WARNING**: The plugin settings have changed a bit, this will also help the MTL section to deal with 3 different sections.  Upgrading to 2.1.2 does not correctly preserve the role-related settings, so after activation, please review the 4 roles settings and set them to the right value. 

Here is a more detailed list of changes.

- Add configuration and code to better decide what to do to role when there is
  a new or expired user. Choices: na, add_role, set_role, remove_role.
- Remove code which to restore a user previous role when he renews. Too confusing.
- Members with status PROC should not be able to login
- Use membership status (instead of valid_to date) as the main criteria to decide if the user is valid or not.
- Print received membership status to log
- Remove Process_Expiry code which used to be run at the end of membership import.
  In theory this is no longer needed however since we do not trust that 2M and local DB
  will always stay in sync,  Add option to check the local database for user expiry.
- Enhance code for sending email to admin, for logging
- During activation phase, if the previous plugin was not 2.1.0, examine
  the user DB and clean-up the previous_roles variable.
- Add setting to limit the number of log files
- Fix PHP error when no email address entered in the Admin to notify option box.

### CODE REVIEW

**Comment by francoisbessette** [comment]
Fully tested, has been running for a month on the Outaouais site. Also tested in the MTL site.

**Comment by keithdunwoody** [comment]
Starting to review, but based on check-in note:

Can you delay removing the "transition from ContactID" code?  I think it will be needed until 2024-05; I've been seeing the code trigger in a few recent cases.

Also not sure I trust 2mev to reliably report expiry.  Might be worth leaving that code, or at least including it as an option.

**Comment by francoisbessette** [comment]
Hi Keith, were you running the good old v2.0.6?
I did a lot of changes recently, but I think it still sits in a branch
called "expire_members_during_data_rx".

Le mar. 26 mars 2024, à 23 h 51, keithdunwoody ***@***.***> a
écrit :

**Comment by keithdunwoody** [comment]
Yes, we're running 2.0.6.

You had this PR for merging your 'expire_members_during_data_rx' branch into main so I thought I'd put a note.  I've seen at least once recently where we're getting member numbers from the API which match expired members in our database.  So at least for Vancouver I think we'll still need that sanity check.

**Comment by francoisbessette** [comment]
1) Yes, I could re-insert the "transition from ContactID" code. But I would like to discuss because I see 2 issues with it:  
as mentioned in the code, if a member was going to change the syntax of his name and at the same time his email (in the 2M database), the plugin would no longer be able to sync him.when I wrote that code, I had in mind the May 2023 migration, where we would receive the same set of existing users but with different numbers for the login_name.  It was meant as a transition aid.  Now that I review the code again, I see the "continue" statement and this could be problematic. If you see this code triggered, it means that a received member from 2M API 'hits' this condition and executes the "continue", which means the update is skipped. We have no choice but skip that user, because we cannot have 2 members in the DB with the same login_name.  But "continue" means a user will not get properly updated in your database.  What caused the code to be triggered?  Was it because some old, expired member (no longer member) still in the Wordpress DB had a ContactID (from old ACC database) which happens to be the same as the 2M member_number of a new member?   If so, maybe you should get rid of those old, expired, non-migrated members.  Or maybe it is because that user changed his name and email at the same time?  For that last condition, the right fix is to remove the code just like I was proposing in the diff.

2) "Also not sure I trust 2mev to reliably report expiry"   Are you talking about the "process_expiry" function which used to run after we finished processing all received data from 2M?  That function was a bit of a backup in case 2M forgot to tell us about an expired user, which was the case in the first few months after migration.  If so, yes I can agree with your point.  I can add an option to optionally run that function at the end of every automatic update.  But be aware that it takes CPU cycles because it cycles through the whole user database.

**Comment by keithdunwoody** [comment]
For #1:  I think it's at least still needed until end of May 2024 (i.e. a month and a bit from now) as that's the last possible time someone could be renewing from the old system to the new one.  Otherwise if the ACC has assigned them a new member number on the new system -- how will we tie this to their old account info?  The new member numbers aren't sent to us as updated members until they renew.

#2 yes, I'm talking about process expiry.  Fair point on being computationally expensive, although it hasn't caused a problem on my deployment so far.  If you want to remove this check I'm not too worried either.

**Comment by francoisbessette** [comment]
1. The code has been added back, mostly by doing git revert 975a8f7 and fixing an easy conflict.
2. the process expiry (actually now called local_db_check) has been added as an option. I also added code to log some interesting stats and warnings.

**Pull request merged**
