### PR TITLE
Expose admin logging function

### PR DESCRIPTION
**Pull request by keithdunwoody**
Expose a function to allow logging to the user importer admin log. The intent is to allow allow hooks which trigger on renewal process to add their own log messages into the renewal logs.

### CODE REVIEW

**Comment by keithdunwoody** [comment]
Not sure if this is the right way to do this -- but I was writing a (non-trivial) renewal hook and was looking for somewhere to log results.

**Comment by francoisbessette** [comment]
I will review the code this week. Can you tell me about you? Which section
are you with?
Francois, webmaster for acc Outaouais

Le dim. 24 sept. 2023, 18 h 55, keithdunwoody ***@***.***> a
écrit :

**Comment by keithdunwoody** [comment]
I'm the new ACC Vancouver section webmaster.  This is in support of Discord integration which the Vancouver section is experimenting with (if I ever get the time to finish it!)

Note that my day job is embedded -- I haven't touched PHP in many, many years before this, so any comments are appreciated.

**Comment by francoisbessette** [comment]
Thanks! On my side I am far from being expert too, I was an embedded
programmer for Cisco and retired 2 years ago. Fortunately I can compensate
with time and experiment.  😀

Le dim. 24 sept. 2023, 21 h 37, keithdunwoody ***@***.***> a
écrit :

**Comment by keithdunwoody** [comment]
Have you had a chance to look at this?

**Comment by francoisbessette** [comment]
Darn, i completely forgot.  Next Monday I should have time.

Le mer. 25 oct. 2023, 22 h 49, keithdunwoody ***@***.***> a
écrit :

**Comment by francoisbessette** [comment]
Hi, I just realized I never reviewed your changes.  Are you still available
to discuss the changes?  I would be more than happy to merge it, but I need
help understand the goal.  And understand the interface with Discord.
Would it be possible to setup a virtual meeting?  I can set it up with
Google meet if that works for you, but I guess I need your email address.
François
***@***.***
819-592-3689 Ottawa timezone

Le mer. 25 oct. 2023, à 22 h 49, keithdunwoody ***@***.***> a
écrit :

**Comment by keithdunwoody** [comment]
Either Google Meet or Zoom works for me; probably Wednesday or Friday would work best for me.

Your email got censored for me; maybe github doesn't like comments with emails?  You can contact me via my accvancouver.ca email listed on https://accvancouver.ca/contact-us/.

**Pull request merged**
